package me.grate.casemanager.database;

import me.grate.casemanager.CaseManager;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseTables {

    private DatabaseTables() {
    }

    public static void createTables(
            CaseManager plugin,
            DatabaseManager database
    ) {

        try (
                Connection connection = database.getConnection();
                Statement statement = connection.createStatement()
        ) {

            /*
             * =========================================================
             * CASES
             * =========================================================
             */

            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS cases (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    target_uuid VARCHAR(36) NOT NULL,
                    target_name VARCHAR(16),
                    creator_uuid VARCHAR(36) NOT NULL,
                    creator_name VARCHAR(16),
                    reason TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id)
                )
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_target_uuid
                ON cases (target_uuid)
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_creator_uuid
                ON cases (creator_uuid)
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_status
                ON cases (status)
            """);


            /*
             * =========================================================
             * CASE NOTES
             * =========================================================
             */

            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS case_notes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    case_id BIGINT NOT NULL,
                    author_uuid VARCHAR(36) NOT NULL,
                    author_name VARCHAR(16),
                    content TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    CONSTRAINT fk_notes_case
                        FOREIGN KEY (case_id)
                        REFERENCES cases(id)
                        ON DELETE CASCADE
                )
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_case_notes_case_id
                ON case_notes (case_id)
            """);


            /*
             * =========================================================
             * CASE EVIDENCE
             * =========================================================
             *
             * content remains available for normal text evidence:
             *
             *   chat logs
             *   staff observations
             *   URLs
             *   anti-cheat information
             *   CoreProtect results
             *   LiteBans results
             *   etc.
             *
             * Media files are NOT stored directly in PostgreSQL.
             * Supabase Storage will hold the actual file.
             */

            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS case_evidence (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    case_id BIGINT NOT NULL,
                    added_by_uuid VARCHAR(36) NOT NULL,
                    added_by_name VARCHAR(16),
                    type VARCHAR(32) NOT NULL,
                    content TEXT NOT NULL,

                    storage_path TEXT,
                    original_filename TEXT,
                    mime_type VARCHAR(255),
                    file_size BIGINT,

                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                    PRIMARY KEY (id),

                    CONSTRAINT fk_evidence_case
                        FOREIGN KEY (case_id)
                        REFERENCES cases(id)
                        ON DELETE CASCADE
                )
            """);

            /*
             * Existing installations may already have the
             * case_evidence table without the media columns.
             *
             * These migrations safely add the new columns.
             */

            statement.executeUpdate("""
                ALTER TABLE case_evidence
                ADD COLUMN IF NOT EXISTS storage_path TEXT
            """);

            statement.executeUpdate("""
                ALTER TABLE case_evidence
                ADD COLUMN IF NOT EXISTS original_filename TEXT
            """);

            statement.executeUpdate("""
                ALTER TABLE case_evidence
                ADD COLUMN IF NOT EXISTS mime_type VARCHAR(255)
            """);

            statement.executeUpdate("""
                ALTER TABLE case_evidence
                ADD COLUMN IF NOT EXISTS file_size BIGINT
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_case_evidence_case_id
                ON case_evidence (case_id)
            """);

            /*
             * Useful when filtering evidence by type, for example:
             *
             * IMAGE
             * VIDEO
             * SCREENSHOT
             * CHAT_LOG
             * COREPROTECT
             * VULCAN
             * LITEBANS
             * NOTE
             */

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_case_evidence_type
                ON case_evidence (type)
            """);


            /*
             * =========================================================
             * CASE INVESTIGATORS
             * =========================================================
             */

            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS case_investigators (
                    case_id BIGINT NOT NULL,
                    investigator_uuid VARCHAR(36) NOT NULL,
                    investigator_name VARCHAR(16),
                    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                    PRIMARY KEY (case_id, investigator_uuid),

                    CONSTRAINT fk_investigator_case
                        FOREIGN KEY (case_id)
                        REFERENCES cases(id)
                        ON DELETE CASCADE
                )
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_investigator_uuid
                ON case_investigators (investigator_uuid)
            """);


            /*
             * =========================================================
             * CASE TIMELINE
             * ========================================================= */

            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS case_timeline (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    case_id BIGINT NOT NULL,
                    actor_uuid VARCHAR(36),
                    actor_name VARCHAR(16),
                    action VARCHAR(64) NOT NULL,
                    details TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                    PRIMARY KEY (id),

                    CONSTRAINT fk_timeline_case
                        FOREIGN KEY (case_id)
                        REFERENCES cases(id)
                        ON DELETE CASCADE
                )
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_timeline_case_id
                ON case_timeline (case_id)
            """);

            statement.executeUpdate("""
                CREATE INDEX IF NOT EXISTS idx_timeline_action
                ON case_timeline (action)
            """);


            /*
             * =========================================================
             * SUCCESS
             * ========================================================= */

            plugin.getLogger().info(
                    "PostgreSQL database tables verified successfully."
            );

            plugin.getLogger().info(
                    "Case evidence media metadata schema verified successfully."
            );

        } catch (SQLException exception) {

            plugin.getLogger().severe(
                    "Failed to create or verify CaseManager PostgreSQL tables."
            );

            throw new IllegalStateException(
                    "PostgreSQL database schema initialization failed.",
                    exception
            );
        }
    }
}